# mkdocs.yml

site_name: Elyth Documentation
site_url: https://elythhq.github.io/elyth-docs/ 
repo_url: https://github.com/ElythHQ/elyth-docs 
repo_name: ElythHQ/elyth-docs

# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs 
    - navigation.sections 
    - toc.integrate 
    - search.suggest 
    - search.highlight 
    - content.tabs.link 
    - content.code.copy 
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4 # Sun icon
        name: Switch to dark mode
    - scheme: slate # Dark mode
      toggle:
        icon: material/brightness-7 # Moon icon
        name: Switch to light mode
  icon:
    logo: material/book-education # A suitable icon for docs


nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Reference:
    - Common Action Verbs: actions.md
    - Available Variables: variables.md
  - Event Handling: events.md 
  - Advanced Topics: advanced.md 


markdown_extensions:
  - admonition 
  - pymdownx.details 
  - pymdownx.superfences 
  - pymdownx.highlight 
  - attr_list 
  - toc: # table 
      permalink: true # permalinks to headings
  - def_list # Definition lists
  - footnotes # Footnotes
  - pymdownx.caret # ^^ syntax
  - pymdownx.mark # == syntax
  - pymdownx.tilde # ~~ syntax
  - pymdownx.critic # Critic markup
  - pymdownx.tasklist: # Checkboxes
      custom_checkbox: true
  - pymdownx.emoji: # Emojis
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed: # Tabs
      alternate_style: true

plugins:
  - search